Repository Dogpamines/DogSeek-Backend, pull requests merged in 2024-06, with the labels that each got.

#16 [FEATURE][PRODUCTS] 사료 전체 조회
  http/Products.http
  src/main/java/com/dogpamines/dogseek/products/controller/ProductsController.java
  src/main/java/com/dogpamines/dogseek/products/model/dao/ProductsMapper.java
  src/main/java/com/dogpamines/dogseek/products/model/dto/ProductsDTO.java
  src/main/java/com/dogpamines/dogseek/products/model/service/ProductsService.java
  src/main/resources/mappers/products/ProductsMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#17 [FEATURE][PRODUCTS] 사료 상세 조회
  http/Products.http
  src/main/java/com/dogpamines/dogseek/products/controller/ProductsController.java
  src/main/java/com/dogpamines/dogseek/products/model/dao/ProductsMapper.java
  src/main/java/com/dogpamines/dogseek/products/model/service/ProductsService.java
  src/main/resources/mappers/products/ProductsMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#18 [FEATURE][DICTIONARY] 견종 전체 조회
  http/dict.http
  src/main/java/com/dogpamines/dogseek/dict/controller/DictController.java
  src/main/java/com/dogpamines/dogseek/dict/model/dao/DictMapper.java
  src/main/java/com/dogpamines/dogseek/dict/model/dto/DictDTO.java
  src/main/java/com/dogpamines/dogseek/dict/model/service/DictService.java
  src/main/java/com/dogpamines/dogseek/dogs/controller/DogsController.java
  src/main/java/com/dogpamines/dogseek/dogs/model/dao/DogsMapper.java
  src/main/java/com/dogpamines/dogseek/dogs/model/dto/DogsDTO.java
  src/main/java/com/dogpamines/dogseek/dogs/model/service/DogsService.java
  src/main/resources/application.yml
  src/main/resources/mappers/dict/DictMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#19 [FEATURE][DICTIONARY] 견종 상세 조회
  http/dict.http
  src/main/java/com/dogpamines/dogseek/dict/controller/DictController.java
  src/main/java/com/dogpamines/dogseek/dict/model/dao/DictMapper.java
  src/main/java/com/dogpamines/dogseek/dict/model/service/DictService.java
Labels: ✨ Feature, :pager: BackEnd

#20 [FEATURE][PRODUCTS] 사료 비교 조회
  http/Products.http
  src/main/java/com/dogpamines/dogseek/products/controller/ProductsController.java
  src/main/java/com/dogpamines/dogseek/products/model/dao/ProductsMapper.java
  src/main/java/com/dogpamines/dogseek/products/model/service/ProductsService.java
  src/main/resources/mappers/products/ProductsMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#21 [FEATURE][PRODUCTS] 사료 검색
  http/Products.http
  src/main/java/com/dogpamines/dogseek/products/controller/ProductsController.java
  src/main/java/com/dogpamines/dogseek/products/model/dao/ProductsMapper.java
  src/main/java/com/dogpamines/dogseek/products/model/service/ProductsService.java
  src/main/resources/mappers/products/ProductsMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#22 [FEATURE][CURATION] 큐레이션 조건 등록
  http/curation.http
  src/main/java/com/dogpamines/dogseek/curation/controller/CurationController.java
  src/main/java/com/dogpamines/dogseek/curation/model/dao/CurationMapper.java
  src/main/java/com/dogpamines/dogseek/curation/model/dto/CurationDTO.java
  src/main/java/com/dogpamines/dogseek/curation/model/service/CurationService.java
  src/main/resources/mappers/curation/CurationMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#23 [Close #13] 견종 검색 구현
  http/dict.http
  src/main/java/com/dogpamines/dogseek/dict/controller/DictController.java
  src/main/java/com/dogpamines/dogseek/dict/model/dao/DictMapper.java
  src/main/java/com/dogpamines/dogseek/dict/model/service/DictService.java
Labels: ✨ Feature, :pager: BackEnd

#25 [Close #24] 사료 추천
  http/curation.http
  http/products.http
  src/main/java/com/dogpamines/dogseek/curation/controller/CurationController.java
  src/main/java/com/dogpamines/dogseek/curation/model/dao/CurationMapper.java
  src/main/java/com/dogpamines/dogseek/curation/model/service/CurationService.java
  src/main/resources/mappers/curation/CurationMapper.xml
  src/main/resources/mappers/products/ProductsMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#37 [#32]admin_product
  http/products.http
  src/main/java/com/dogpamines/dogseek/config/WebMvcConfig.java
  src/main/java/com/dogpamines/dogseek/products/controller/ProductsController.java
  src/main/java/com/dogpamines/dogseek/products/model/dao/ProductsMapper.java
  src/main/java/com/dogpamines/dogseek/products/model/service/ProductsService.java
  src/main/resources/mappers/products/ProductsMapper.xml
Labels: ✨ Feature, :pager: BackEnd, 📬 API

#34 [close #35] 게시글 목록 전체 조회
  http/board.http
  src/main/java/com/dogpamines/dogseek/board/controller/BoardController.java
  src/main/java/com/dogpamines/dogseek/board/model/dao/BoardMapper.java
  src/main/java/com/dogpamines/dogseek/board/model/dto/BoardDTO.java
  src/main/java/com/dogpamines/dogseek/board/model/service/BoardService.java
  src/main/resources/mappers/board/BoardMapper.xml
Labels: :pager: BackEnd

#27 [close #26] 환경 설정
  build.gradle
  src/main/java/com/dogpamines/dogseek/config/WebMvcConfig.java
  src/main/java/com/dogpamines/dogseek/config/WebSecurityConfig.java
Labels: ⚙ Setting, :pager: BackEnd

#29 [close #28] 로그인 핸들러 구현
  src/main/java/com/dogpamines/dogseek/auth/handler/CustomAuthFailureHandler.java
  src/main/java/com/dogpamines/dogseek/auth/handler/CustomAuthSuccessHandler.java
  src/main/java/com/dogpamines/dogseek/auth/handler/CustomAuthenticationProvider.java
  src/main/java/com/dogpamines/dogseek/auth/model/DetailsUser.java
  src/main/java/com/dogpamines/dogseek/auth/model/service/DetailsService.java
  src/main/java/com/dogpamines/dogseek/common/AuthConstants.java
  src/main/java/com/dogpamines/dogseek/common/UserRole.java
  src/main/java/com/dogpamines/dogseek/common/utils/ConvertUtil.java
  src/main/java/com/dogpamines/dogseek/common/utils/ConvertUtils.java
  src/main/java/com/dogpamines/dogseek/common/utils/TokenUtils.java
  src/main/java/com/dogpamines/dogseek/user/model/dao/UserMapper.java
  src/main/java/com/dogpamines/dogseek/user/model/dto/UserDTO.java
  src/main/java/com/dogpamines/dogseek/user/model/service/UserService.java
Labels: ✨ Feature, :pager: BackEnd

#31 [close #30] 로그인 필터 구현
  src/main/java/com/dogpamines/dogseek/auth/filter/CustomAuthenticationFilter.java
  src/main/java/com/dogpamines/dogseek/auth/filter/HandlerFilter.java
  src/main/java/com/dogpamines/dogseek/auth/filter/HeaderFilter.java
Labels: ✨ Feature, :pager: BackEnd

#41 [#32]admin products page
  http/products.http
  src/main/java/com/dogpamines/dogseek/products/controller/ProductsController.java
  src/main/java/com/dogpamines/dogseek/products/model/dto/ProductsDTO.java
  src/main/resources/mappers/products/ProductsMapper.xml
Labels: :pager: BackEnd, 📬 API

#40 [close #39] 회원가입 기능 구현
  http/user.http
  src/main/java/com/dogpamines/dogseek/auth/filter/CustomAuthenticationFilter.java
  src/main/java/com/dogpamines/dogseek/auth/filter/HeaderFilter.java
  src/main/java/com/dogpamines/dogseek/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/dogpamines/dogseek/auth/handler/CustomAuthFailureHandler.java
  src/main/java/com/dogpamines/dogseek/auth/handler/CustomAuthSuccessHandler.java
  src/main/java/com/dogpamines/dogseek/auth/handler/CustomAuthenticationProvider.java
  src/main/java/com/dogpamines/dogseek/auth/model/DetailsUser.java
  src/main/java/com/dogpamines/dogseek/auth/model/service/DetailsService.java
  src/main/java/com/dogpamines/dogseek/common/utils/ConvertUtil.java
  src/main/java/com/dogpamines/dogseek/common/utils/TokenUtils.java
  src/main/java/com/dogpamines/dogseek/config/WebMvcConfig.java
  src/main/java/com/dogpamines/dogseek/config/WebSecurityConfig.java
  src/main/java/com/dogpamines/dogseek/user/controller/UserController.java
  src/main/java/com/dogpamines/dogseek/user/model/dao/UserMapper.java
  src/main/java/com/dogpamines/dogseek/user/model/service/UserService.java
  src/main/resources/mappers/user/UserMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#42 [close #38] 로그인 기능 구현
  build.gradle
  http/user.http
  src/main/java/com/dogpamines/dogseek/auth/filter/HeaderFilter.java
  src/main/java/com/dogpamines/dogseek/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/dogpamines/dogseek/config/WebMvcConfig.java
  src/main/java/com/dogpamines/dogseek/config/WebSecurityConfig.java
  src/main/java/com/dogpamines/dogseek/user/controller/UserController.java
  src/main/java/com/dogpamines/dogseek/user/model/service/UserService.java
  src/main/resources/mappers/user/UserMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#45 [#32]admin pages
  http/dict.http
  src/main/java/com/dogpamines/dogseek/config/WebSecurityConfig.java
  src/main/java/com/dogpamines/dogseek/dict/controller/DictController.java
  src/main/java/com/dogpamines/dogseek/dict/model/dao/DictMapper.java
  src/main/java/com/dogpamines/dogseek/dict/model/service/DictService.java
  src/main/resources/mappers/dict/DictMapper.xml
Labels: ✨ Feature, :pager: BackEnd, 📬 API

#46 [#44] 큐레이션 사료 저장
  http/curation.http
  src/main/java/com/dogpamines/dogseek/curation/controller/CurationController.java
  src/main/java/com/dogpamines/dogseek/curation/model/dao/CurationMapper.java
  src/main/java/com/dogpamines/dogseek/curation/model/dto/HistoryDTO.java
  src/main/java/com/dogpamines/dogseek/curation/model/service/CurationService.java
  src/main/resources/mappers/curation/CurationMapper.xml
Labels: :pager: BackEnd, 📬 API

#48 [#47] User's curation list
  http/mypage.http
  src/main/java/com/dogpamines/dogseek/curation/model/dto/CurationDTO.java
  src/main/java/com/dogpamines/dogseek/mypage/controller/MyPageController.java
  src/main/java/com/dogpamines/dogseek/mypage/model/dao/MyPageMapper.java
  src/main/java/com/dogpamines/dogseek/mypage/model/service/MyPageService.java
  src/main/resources/mappers/mypage/MypageMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#51 [#36] View post details page complete
  http/board.http
  src/main/java/com/dogpamines/dogseek/board/controller/BoardController.java
  src/main/java/com/dogpamines/dogseek/board/model/dao/BoardMapper.java
  src/main/java/com/dogpamines/dogseek/board/model/service/BoardService.java
  src/main/resources/mappers/board/BoardMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#50 [#13] Dog search
  src/main/java/com/dogpamines/dogseek/dict/controller/DictController.java
Labels: ✨ Feature, :pager: BackEnd

#52 [#44] Curation Insert History
  src/main/java/com/dogpamines/dogseek/curation/controller/CurationController.java
  src/main/java/com/dogpamines/dogseek/curation/model/dao/CurationMapper.java
  src/main/java/com/dogpamines/dogseek/curation/model/service/CurationService.java
  src/main/resources/mappers/curation/CurationMapper.xml
Labels: ✨ Feature, 📬 API

#53 [#32] Admin_user page
  http/user.http
  src/main/java/com/dogpamines/dogseek/board/model/dto/BoardAndCommentDTO.java
  src/main/java/com/dogpamines/dogseek/board/model/dto/CommentDTO.java
  src/main/java/com/dogpamines/dogseek/common/UserRole.java
  src/main/java/com/dogpamines/dogseek/curation/model/dao/CurationMapper.java
  src/main/java/com/dogpamines/dogseek/curation/model/service/CurationService.java
  src/main/java/com/dogpamines/dogseek/user/controller/UserController.java
  src/main/java/com/dogpamines/dogseek/user/model/dao/UserMapper.java
  src/main/java/com/dogpamines/dogseek/user/model/service/UserService.java
  src/main/resources/mappers/curation/CurationMapper.xml
  src/main/resources/mappers/user/UserMapper.xml
Labels: ✨ Feature, :pager: BackEnd, 📬 API

#55 [#49] User info select,update, delete
  http/mypage.http
  src/main/java/com/dogpamines/dogseek/mypage/controller/MyPageController.java
  src/main/java/com/dogpamines/dogseek/mypage/model/dao/MyPageMapper.java
  src/main/java/com/dogpamines/dogseek/mypage/model/service/MyPageService.java
  src/main/resources/mappers/mypage/MypageMapper.xml
Labels: ✨ Feature, :pager: BackEnd, 📬 API

#56 [#44] Curation Insert History
  http/curation.http
  src/main/java/com/dogpamines/dogseek/curation/model/dto/HistoryDTO.java
  src/main/resources/mappers/curation/CurationMapper.xml
Labels: 🐞 BugFix, ✨ Feature, :pager: BackEnd, 📬 API

#57 [#54] Write a post
  http/board.http
  src/main/java/com/dogpamines/dogseek/board/controller/BoardController.java
  src/main/java/com/dogpamines/dogseek/board/model/dao/BoardMapper.java
  src/main/java/com/dogpamines/dogseek/board/model/service/BoardService.java
  src/main/resources/mappers/board/BoardMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#61 [ #60 ] dictdetail data update
  src/main/resources/mappers/dict/DictMapper.xml
Labels: :pager: BackEnd

#63 [#32] Admin user & board pages
  http/board.http
  src/main/java/com/dogpamines/dogseek/board/controller/BoardController.java
  src/main/java/com/dogpamines/dogseek/board/model/dao/BoardMapper.java
  src/main/java/com/dogpamines/dogseek/board/model/service/BoardService.java
  src/main/resources/mappers/board/BoardMapper.xml
  src/main/resources/mappers/curation/CurationMapper.xml
Labels: ✨ Feature, :pager: BackEnd, 📬 API

#65 [#59] My Page controller / mapper edit
  http/mypage.http
  src/main/java/com/dogpamines/dogseek/mypage/controller/MyPageController.java
  src/main/java/com/dogpamines/dogseek/mypage/model/dao/MyPageMapper.java
  src/main/java/com/dogpamines/dogseek/mypage/model/service/MyPageService.java
  src/main/resources/mappers/mypage/MypageMapper.xml
Labels: :pager: BackEnd, 🔨 Refactor, 📬 API

#69 [#68] Pass value(dogName) to dogDetailPage
  src/main/java/com/dogpamines/dogseek/dict/controller/DictController.java
  src/main/java/com/dogpamines/dogseek/dict/model/dao/DictMapper.java
  src/main/java/com/dogpamines/dogseek/dict/model/service/DictService.java
  src/main/resources/mappers/dict/DictMapper.xml
Labels: 🐞 BugFix, ✨ Feature

#72 [#71] Nickname duplication check
  http/user.http
  src/main/java/com/dogpamines/dogseek/user/controller/UserController.java
  src/main/java/com/dogpamines/dogseek/user/model/dao/UserMapper.java
  src/main/java/com/dogpamines/dogseek/user/model/service/UserService.java
  src/main/resources/mappers/user/UserMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#74 [#73] Email duplication check
  http/user.http
  src/main/java/com/dogpamines/dogseek/user/controller/UserController.java
  src/main/java/com/dogpamines/dogseek/user/model/dao/UserMapper.java
  src/main/java/com/dogpamines/dogseek/user/model/service/UserService.java
  src/main/resources/mappers/user/UserMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#75 [#67] Admin_counting
  build.gradle
  src/main/java/com/dogpamines/dogseek/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/dogpamines/dogseek/common/model/RedisService.java
  src/main/java/com/dogpamines/dogseek/config/RedisConfig.java
  src/main/java/com/dogpamines/dogseek/redistTest/CacheService.java
  src/main/java/com/dogpamines/dogseek/redistTest/LoginController.java
  src/main/java/com/dogpamines/dogseek/redistTest/LoginService.java
  src/main/java/com/dogpamines/dogseek/redistTest/Member.java
  src/main/java/com/dogpamines/dogseek/redistTest/MemberRepository.java
Labels: ✨ Feature, :pager: BackEnd

#77 [#54] Post writing
  http/board.http
  src/main/java/com/dogpamines/dogseek/board/controller/BoardController.java
  src/main/java/com/dogpamines/dogseek/board/model/dao/BoardMapper.java
  src/main/java/com/dogpamines/dogseek/board/model/dto/ChatBoardDTO.java
  src/main/java/com/dogpamines/dogseek/board/model/service/BoardService.java
  src/main/resources/mappers/board/BoardMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#70 [#66] JWT token interceptor create
  http/user.http
  src/main/java/com/dogpamines/dogseek/auth/filter/CustomAuthenticationFilter.java
  src/main/java/com/dogpamines/dogseek/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/dogpamines/dogseek/auth/handler/CustomAuthFailureHandler.java
  src/main/java/com/dogpamines/dogseek/auth/handler/CustomAuthSuccessHandler.java
  src/main/java/com/dogpamines/dogseek/auth/handler/CustomAuthenticationProvider.java
  src/main/java/com/dogpamines/dogseek/auth/interceptor/JwtTokenInterceptor.java
  src/main/java/com/dogpamines/dogseek/auth/model/DetailsUser.java
  src/main/java/com/dogpamines/dogseek/auth/model/service/DetailsService.java
  src/main/java/com/dogpamines/dogseek/common/utils/TokenUtils.java
  src/main/java/com/dogpamines/dogseek/config/WebMvcConfig.java
  src/main/java/com/dogpamines/dogseek/config/WebSecurityConfig.java
Labels: ✨ Feature, :pager: BackEnd, 📬 API

#82 [#67] Counting products visit
  http/user.http
  src/main/java/com/dogpamines/dogseek/common/model/RedisService.java
  src/main/java/com/dogpamines/dogseek/common/model/dao/ScheduledMapper.java
  src/main/java/com/dogpamines/dogseek/common/model/dto/CountsDTO.java
  src/main/java/com/dogpamines/dogseek/common/model/service/RedisService.java
  src/main/java/com/dogpamines/dogseek/common/model/service/ScheduledService.java
  src/main/java/com/dogpamines/dogseek/products/controller/ProductsController.java
  src/main/java/com/dogpamines/dogseek/products/model/dao/ProductsMapper.java
  src/main/java/com/dogpamines/dogseek/products/model/dto/ProductsDTO.java
  src/main/java/com/dogpamines/dogseek/products/model/service/ProductsService.java
  src/main/resources/mappers/common/ScheduledMapper.xml
  src/main/resources/mappers/products/ProductsMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#86 [#85] Products List
  http/products.http
  src/main/java/com/dogpamines/dogseek/auth/filter/JwtAuthorizationFilter.java
  src/main/resources/mappers/products/ProductsMapper.xml
Labels: :pager: BackEnd, 📬 API

#84 [#80] Vaildate user information
  build.gradle
  http/user.http
  src/main/java/com/dogpamines/dogseek/common/controller/ExceptionController.java
  src/main/java/com/dogpamines/dogseek/common/dto/ErrorDTO.java
  src/main/java/com/dogpamines/dogseek/user/controller/UserController.java
  src/main/java/com/dogpamines/dogseek/user/model/dto/UserDTO.java
Labels: ⚙ Setting, ✨ Feature, :pager: BackEnd

#83 [#81] Latest prod list
  http/main.http
  src/main/java/com/dogpamines/dogseek/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/dogpamines/dogseek/main/controller/MainController.java
  src/main/java/com/dogpamines/dogseek/main/model/dao/MainMapper.java
  src/main/java/com/dogpamines/dogseek/main/model/service/MainService.java
  src/main/resources/mappers/main/MainMapper.xml
Labels: ✨ Feature, :pager: BackEnd
