Repository Dogpamines/DogSeek-Backend, pull requests merged in 2024-07, with the labels that each got.

#90 [#32] Admin main page
  http/admin.http
  http/user.http
  src/main/java/com/dogpamines/dogseek/admin/controller/AdminController.java
  src/main/java/com/dogpamines/dogseek/admin/controller/AdminMainController.java
  src/main/java/com/dogpamines/dogseek/admin/model/dao/AdminMapper.java
  src/main/java/com/dogpamines/dogseek/admin/model/service/AdminService.java
  src/main/java/com/dogpamines/dogseek/common/model/service/ScheduledService.java
  src/main/java/com/dogpamines/dogseek/products/model/dto/ProductsDTO.java
  src/main/resources/mappers/admin/AdminMapper.xml
  src/main/resources/mappers/common/ScheduledMapper.xml
Labels: ✨ Feature, :pager: BackEnd, 📬 API

#91 [#87] Fix signup
  http/user.http
  src/main/java/com/dogpamines/dogseek/user/controller/UserController.java
  src/main/java/com/dogpamines/dogseek/user/model/service/UserService.java
  src/main/resources/mappers/user/UserMapper.xml
Labels: :pager: BackEnd, 🔨 Refactor

#92 [#89] Fix login
  src/main/java/com/dogpamines/dogseek/auth/handler/CustomAuthSuccessHandler.java
Labels: :pager: BackEnd, 🔨 Refactor

#93 [#88] Email verification
  build.gradle
  http/email.http
  src/main/java/com/dogpamines/dogseek/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/dogpamines/dogseek/common/controller/EmailVerificationController.java
  src/main/java/com/dogpamines/dogseek/common/controller/ExceptionController.java
  src/main/java/com/dogpamines/dogseek/common/model/dto/ErrorDTO.java
  src/main/java/com/dogpamines/dogseek/common/model/service/EmailService.java
  src/main/java/com/dogpamines/dogseek/common/model/service/VerificationService.java
Labels: ⚙ Setting, ✨ Feature, :pager: BackEnd

#96 [#32] Admin pages (validate & exception)
  src/main/java/com/dogpamines/dogseek/dict/controller/DictController.java
  src/main/java/com/dogpamines/dogseek/dict/model/dao/DictMapper.java
  src/main/java/com/dogpamines/dogseek/dict/model/service/DictService.java
  src/main/resources/mappers/dict/DictMapper.xml
Labels: 🐞 BugFix, 🔨 Refactor, 📬 API

#97 [#95] CURATION WITH HISTORY
  http/mypage.http
  src/main/java/com/dogpamines/dogseek/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/dogpamines/dogseek/mypage/controller/MyPageController.java
  src/main/java/com/dogpamines/dogseek/mypage/model/dao/MyPageMapper.java
  src/main/java/com/dogpamines/dogseek/mypage/model/service/MyPageService.java
  src/main/resources/mappers/mypage/MypageMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#98 [#85] Products List
  src/main/java/com/dogpamines/dogseek/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/dogpamines/dogseek/products/controller/ProductsController.java
  src/main/java/com/dogpamines/dogseek/products/model/dao/ProductsMapper.java
  src/main/java/com/dogpamines/dogseek/products/model/service/ProductsService.java
  src/main/resources/mappers/products/ProductsMapper.xml
Labels: ✨ Feature, :pager: BackEnd, 📬 API

#99 [#94] Update login latest date
  src/main/java/com/dogpamines/dogseek/auth/filter/CustomAuthenticationFilter.java
  src/main/java/com/dogpamines/dogseek/auth/model/service/DetailsService.java
  src/main/java/com/dogpamines/dogseek/user/model/dao/UserMapper.java
  src/main/java/com/dogpamines/dogseek/user/model/service/UserService.java
  src/main/resources/mappers/user/UserMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#103 [#32] Admin pages
  src/main/java/com/dogpamines/dogseek/dict/controller/DictController.java
  src/main/java/com/dogpamines/dogseek/user/controller/UserController.java
  src/main/java/com/dogpamines/dogseek/user/model/service/UserService.java
  src/main/resources/mappers/dict/DictMapper.xml
Labels: 🐞 BugFix, ✨ Feature, :pager: BackEnd, 🔨 Refactor, 📬 API

#104 [#100] Find user account
  http/email.http
  http/user.http
  src/main/java/com/dogpamines/dogseek/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/dogpamines/dogseek/common/controller/EmailVerificationController.java
  src/main/java/com/dogpamines/dogseek/user/controller/UserController.java
  src/main/java/com/dogpamines/dogseek/user/model/dao/UserMapper.java
  src/main/java/com/dogpamines/dogseek/user/model/service/UserService.java
  src/main/resources/mappers/user/UserMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#105 [#102] Animal Registration Number commit
  http/animalRegist.http
  src/main/java/com/dogpamines/dogseek/animalRegist/controller/AnimalRegistController.java
  src/main/java/com/dogpamines/dogseek/auth/filter/JwtAuthorizationFilter.java
Labels: ✨ Feature, :pager: BackEnd, 📬 API

#108 [#107] Fix login update
  src/main/java/com/dogpamines/dogseek/auth/model/service/DetailsService.java
Labels: 🐞 BugFix, :pager: BackEnd

#109 [#54] post writing
  http/board.http
  src/main/java/com/dogpamines/dogseek/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/dogpamines/dogseek/board/controller/BoardController.java
  src/main/java/com/dogpamines/dogseek/board/model/dao/BoardMapper.java
  src/main/java/com/dogpamines/dogseek/board/model/dto/BoardChatDTO.java
  src/main/java/com/dogpamines/dogseek/board/model/service/BoardService.java
  src/main/resources/mappers/board/BoardMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#111 [#106] MY PAGE EDIT
  http/mypage.http
  src/main/java/com/dogpamines/dogseek/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/dogpamines/dogseek/mypage/controller/MyPageController.java
  src/main/java/com/dogpamines/dogseek/mypage/model/dao/MyPageMapper.java
  src/main/java/com/dogpamines/dogseek/mypage/model/service/MyPageService.java
  src/main/resources/mappers/mypage/MypageMapper.xml
Labels: ✨ Feature, :pager: BackEnd, 📬 API

#112 [#32] Admin pages
  src/main/java/com/dogpamines/dogseek/admin/model/service/AdminService.java
  src/main/java/com/dogpamines/dogseek/common/model/service/RedisService.java
  src/main/java/com/dogpamines/dogseek/common/model/service/ScheduledService.java
  src/main/java/com/dogpamines/dogseek/curation/model/dao/CurationMapper.java
  src/main/java/com/dogpamines/dogseek/curation/model/service/CurationService.java
  src/main/java/com/dogpamines/dogseek/products/controller/ProductsController.java
  src/main/java/com/dogpamines/dogseek/products/model/service/ProductsService.java
  src/main/java/com/dogpamines/dogseek/user/controller/UserController.java
  src/main/java/com/dogpamines/dogseek/user/model/dao/UserMapper.java
  src/main/java/com/dogpamines/dogseek/user/model/service/UserService.java
  src/main/resources/mappers/curation/CurationMapper.xml
  src/main/resources/mappers/user/UserMapper.xml
Labels: ✨ Feature, :pager: BackEnd, 🔨 Refactor, 📬 API

#113 [#85] Products List
  src/main/resources/mappers/products/ProductsMapper.xml
Labels: 🔨 Refactor

#110 [#102] AnimalRegistrationNumber
  http/animalRegist.http
  src/main/java/com/dogpamines/dogseek/animalRegist/controller/AnimalRegistController.java
  src/main/java/com/dogpamines/dogseek/animalRegist/model/service/AnimalRegistService.java
Labels: ✨ Feature, :pager: BackEnd, 📬 API

#116 [#115] Modify select user id by user phone number
  src/main/java/com/dogpamines/dogseek/user/controller/UserController.java
  src/main/java/com/dogpamines/dogseek/user/model/dao/UserMapper.java
  src/main/java/com/dogpamines/dogseek/user/model/service/UserService.java
  src/main/resources/mappers/user/UserMapper.xml
Labels: :pager: BackEnd, 🔨 Refactor

#117 [#106,#95] Edit Nickname & Call Prod
  http/mypage.http
  src/main/java/com/dogpamines/dogseek/mypage/controller/MyPageController.java
  src/main/java/com/dogpamines/dogseek/mypage/model/dao/MyPageMapper.java
  src/main/java/com/dogpamines/dogseek/mypage/model/service/MyPageService.java
  src/main/resources/mappers/mypage/MypageMapper.xml
Labels: ✨ Feature, :pager: BackEnd, 📬 API

#118 [#32] Admin pages
  src/main/java/com/dogpamines/dogseek/board/controller/BoardController.java
  src/main/java/com/dogpamines/dogseek/board/model/dao/BoardMapper.java
  src/main/java/com/dogpamines/dogseek/board/model/service/BoardService.java
  src/main/java/com/dogpamines/dogseek/user/model/service/UserService.java
  src/main/resources/mappers/board/BoardMapper.xml
Labels: ✨ Feature, :pager: BackEnd, 🔨 Refactor

#122 [#121] Admin count new board
  src/main/java/com/dogpamines/dogseek/admin/model/service/AdminService.java
  src/main/java/com/dogpamines/dogseek/board/model/service/BoardService.java
  src/main/java/com/dogpamines/dogseek/common/model/service/ScheduledService.java
Labels: ✨ Feature, :pager: BackEnd

#123 [#120]Update post
  http/board.http
  src/main/resources/mappers/board/BoardMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#125 [#114] Logout
  http/user.http
  src/main/java/com/dogpamines/dogseek/auth/controller/AuthController.java
  src/main/java/com/dogpamines/dogseek/auth/filter/CustomAuthenticationFilter.java
  src/main/java/com/dogpamines/dogseek/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/dogpamines/dogseek/auth/handler/CustomAuthSuccessHandler.java
  src/main/java/com/dogpamines/dogseek/auth/model/service/RefreshTokenService.java
  src/main/java/com/dogpamines/dogseek/common/utils/TokenUtils.java
  src/main/java/com/dogpamines/dogseek/config/WebSecurityConfig.java
Labels: ✨ Feature, :pager: BackEnd

#126 [#106] Edit password
  http/mypage.http
  src/main/java/com/dogpamines/dogseek/mypage/controller/MyPageController.java
  src/main/java/com/dogpamines/dogseek/mypage/model/dao/MyPageMapper.java
  src/main/java/com/dogpamines/dogseek/mypage/model/service/MyPageService.java
  src/main/resources/mappers/mypage/MypageMapper.xml
Labels: :pager: BackEnd, 🔨 Refactor, 📬 API

#130 [#129] Cookie & view count
  src/main/java/com/dogpamines/dogseek/admin/model/service/AdminService.java
  src/main/java/com/dogpamines/dogseek/common/model/service/RedisService.java
  src/main/java/com/dogpamines/dogseek/common/model/service/ScheduledService.java
  src/main/java/com/dogpamines/dogseek/config/WebSecurityConfig.java
  src/main/java/com/dogpamines/dogseek/products/controller/ProductsController.java
  src/main/java/com/dogpamines/dogseek/products/model/service/ProductsService.java
Labels: ✨ Feature, :pager: BackEnd, 🔨 Refactor, 📬 API

#131 [#106] Edit Password
  http/mypage.http
  src/main/java/com/dogpamines/dogseek/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/dogpamines/dogseek/mypage/controller/MyPageController.java
  src/main/java/com/dogpamines/dogseek/mypage/model/dao/MyPageMapper.java
  src/main/java/com/dogpamines/dogseek/mypage/model/service/MyPageService.java
  src/main/resources/mappers/mypage/MypageMapper.xml
Labels: :pager: BackEnd, 🔨 Refactor, 📬 API

#133 [#128] Add volumeRestApi
  http/products.http
  src/main/java/com/dogpamines/dogseek/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/dogpamines/dogseek/products/controller/ProductsController.java
  src/main/java/com/dogpamines/dogseek/products/model/dao/ProductsMapper.java
  src/main/java/com/dogpamines/dogseek/products/model/service/ProductsService.java
  src/main/resources/mappers/products/ProductsMapper.xml
Labels: ✨ Feature, :pager: BackEnd, 📬 API

#134 [#132] Modify reissuance access token
  src/main/java/com/dogpamines/dogseek/auth/controller/AuthController.java
  src/main/java/com/dogpamines/dogseek/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/dogpamines/dogseek/common/utils/TokenUtils.java
  src/main/java/com/dogpamines/dogseek/user/model/dao/UserMapper.java
  src/main/java/com/dogpamines/dogseek/user/model/service/UserService.java
  src/main/resources/mappers/user/UserMapper.xml
Labels: ✨ Feature, :pager: BackEnd, 🔨 Refactor

#136 [#106] Edit Password
  src/main/java/com/dogpamines/dogseek/mypage/controller/MyPageController.java
  src/main/java/com/dogpamines/dogseek/mypage/model/dao/MyPageMapper.java
  src/main/java/com/dogpamines/dogseek/mypage/model/service/MyPageService.java
  src/main/resources/mappers/mypage/MypageMapper.xml
Labels: ✨ Feature, :pager: BackEnd, 🔨 Refactor

#135 [#127] Update SLEEP to USER
  src/main/java/com/dogpamines/dogseek/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/dogpamines/dogseek/common/controller/EmailVerificationController.java
  src/main/java/com/dogpamines/dogseek/user/controller/UserController.java
  src/main/java/com/dogpamines/dogseek/user/model/dao/UserMapper.java
  src/main/java/com/dogpamines/dogseek/user/model/service/UserService.java
  src/main/resources/mappers/user/UserMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#138 [#137] Redis + Sql PROD_VISIT Merge
  http/products.http
  src/main/java/com/dogpamines/dogseek/products/model/service/ProductsService.java
  src/main/resources/mappers/products/ProductsMapper.xml
Labels: ✨ Feature, :pager: BackEnd, 📬 API

#140 [#139] USER DTO CHANGE
  src/main/java/com/dogpamines/dogseek/common/UserRole.java
  src/main/java/com/dogpamines/dogseek/user/model/dto/UserDTO.java
  src/main/resources/mappers/user/UserMapper.xml
Labels: 📃 Docs, 🔨 Refactor

#142 [#141] Add refresh token to DB
  src/main/java/com/dogpamines/dogseek/auth/controller/AuthController.java
  src/main/java/com/dogpamines/dogseek/auth/handler/CustomAuthSuccessHandler.java
  src/main/java/com/dogpamines/dogseek/auth/model/service/RefreshTokenService.java
  src/main/java/com/dogpamines/dogseek/config/WebSecurityConfig.java
  src/main/java/com/dogpamines/dogseek/user/model/dao/UserMapper.java
  src/main/java/com/dogpamines/dogseek/user/model/dto/UserDTO.java
  src/main/java/com/dogpamines/dogseek/user/model/service/UserService.java
  src/main/resources/mappers/user/UserMapper.xml
Labels: 🐞 BugFix, ✨ Feature, 🔨 Refactor

#143 [#106] Add User_Leave
  src/main/java/com/dogpamines/dogseek/mypage/controller/MyPageController.java
  src/main/resources/mappers/mypage/MypageMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#147 [#146] Edit send email form
  src/main/java/com/dogpamines/dogseek/common/controller/EmailVerificationController.java
  src/main/java/com/dogpamines/dogseek/common/model/service/EmailService.java
  src/main/resources/templates/email.html
Labels: 🎨 Html&css, 🔨 Refactor

#148 [#120] Post update
  http/board.http
  src/main/java/com/dogpamines/dogseek/board/controller/BoardController.java
  src/main/java/com/dogpamines/dogseek/board/model/dao/BoardMapper.java
  src/main/java/com/dogpamines/dogseek/board/model/dto/BoardPostDTO.java
  src/main/java/com/dogpamines/dogseek/board/model/service/BoardService.java
  src/main/resources/mappers/board/BoardMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#150 [#149] Chatting
  build.gradle
  src/main/java/com/dogpamines/dogseek/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/dogpamines/dogseek/common/controller/ChatController.java
  src/main/java/com/dogpamines/dogseek/common/model/dto/ChatMessageDTO.java
  src/main/java/com/dogpamines/dogseek/common/model/dto/CheckDTO.java
  src/main/java/com/dogpamines/dogseek/common/model/service/ChatService.java
  src/main/java/com/dogpamines/dogseek/config/WebMvcConfig.java
  src/main/java/com/dogpamines/dogseek/config/WebSecurityConfig.java
  src/main/java/com/dogpamines/dogseek/config/WebSocketConfig.java
  src/main/java/com/dogpamines/dogseek/config/WebSocketHandler.java
  src/main/java/com/dogpamines/dogseek/config/WebSocketMessageBrokerConfig.java
Labels: ✨ Feature, :pager: BackEnd, 📬 API

#145 [#144] Exception handling related to redis
  src/main/java/com/dogpamines/dogseek/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/dogpamines/dogseek/auth/model/service/RefreshTokenService.java
  src/main/java/com/dogpamines/dogseek/common/model/service/VerificationService.java
  src/main/java/com/dogpamines/dogseek/config/SecurityConfig.java
  src/main/java/com/dogpamines/dogseek/config/WebSecurityConfig.java
Labels: 🐞 BugFix, :pager: BackEnd, 🔨 Refactor

#152 [#151] Fix email form
  src/main/java/com/dogpamines/dogseek/common/model/service/EmailService.java
  src/main/resources/templates/email.html
Labels: 🐞 BugFix, 🎨 Html&css

#154 [#153] GlobalException
  src/main/java/com/dogpamines/dogseek/exception/ErrorCode.java
  src/main/java/com/dogpamines/dogseek/exception/ErrorResponse.java
  src/main/java/com/dogpamines/dogseek/exception/GlobalExceptionHandler.java
Labels: ✨ Feature, :pager: BackEnd

#156 [#155] Swagger
  build.gradle
  src/main/java/com/dogpamines/dogseek/auth/filter/JwtAuthorizationFilter.java
  src/main/java/com/dogpamines/dogseek/config/SwaggerConfig.java
  src/main/java/com/dogpamines/dogseek/config/SwaggerController.java
  src/main/java/com/dogpamines/dogseek/mypage/controller/MyPageController.java
  src/main/java/com/dogpamines/dogseek/products/controller/ProductsController.java
  src/main/java/com/dogpamines/dogseek/products/model/dto/ProductsDTO.java
  src/main/java/com/dogpamines/dogseek/user/controller/UserController.java
  src/main/java/com/dogpamines/dogseek/user/model/dto/UserDTO.java
Labels: 📃 Docs

#157 [#120] Post update
  http/board.http
  src/main/java/com/dogpamines/dogseek/board/controller/BoardController.java
  src/main/java/com/dogpamines/dogseek/board/model/dao/BoardMapper.java
  src/main/java/com/dogpamines/dogseek/board/model/service/BoardService.java
  src/main/resources/mappers/board/BoardMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#159 [#149] chatting
  src/main/java/com/dogpamines/dogseek/common/controller/ChatController.java
  src/main/java/com/dogpamines/dogseek/common/model/service/ChatService.java
  src/main/java/com/dogpamines/dogseek/common/model/service/ScheduledService.java
Labels: ✨ Feature, :pager: BackEnd, 📬 API

#158 [#155] Complete Swagger
  src/main/java/com/dogpamines/dogseek/admin/controller/AdminController.java
  src/main/java/com/dogpamines/dogseek/auth/controller/AuthController.java
  src/main/java/com/dogpamines/dogseek/board/controller/BoardController.java
  src/main/java/com/dogpamines/dogseek/board/model/dto/BoardDTO.java
  src/main/java/com/dogpamines/dogseek/board/model/dto/BoardPostDTO.java
  src/main/java/com/dogpamines/dogseek/common/controller/ChatController.java
  src/main/java/com/dogpamines/dogseek/common/controller/EmailVerificationController.java
  src/main/java/com/dogpamines/dogseek/common/model/dto/ChatMessageDTO.java
  src/main/java/com/dogpamines/dogseek/curation/controller/CurationController.java
  src/main/java/com/dogpamines/dogseek/curation/model/dto/CurationDTO.java
  src/main/java/com/dogpamines/dogseek/curation/model/dto/HistoryDTO.java
  src/main/java/com/dogpamines/dogseek/dict/controller/DictController.java
  src/main/java/com/dogpamines/dogseek/dict/model/dto/DictDTO.java
  src/main/java/com/dogpamines/dogseek/main/controller/MainController.java
  src/main/java/com/dogpamines/dogseek/redistTest/LoginController.java
Labels: 📃 Docs

#162 [#160] Real post report close
  src/main/java/com/dogpamines/dogseek/board/controller/BoardController.java
  src/main/java/com/dogpamines/dogseek/board/model/dao/BoardMapper.java
  src/main/java/com/dogpamines/dogseek/board/model/service/BoardService.java
  src/main/resources/mappers/board/BoardMapper.xml
Labels: ✨ Feature, :pager: BackEnd

#164 [#163] Fix url
  src/main/java/com/dogpamines/dogseek/curation/controller/CurationController.java
  src/main/java/com/dogpamines/dogseek/dict/controller/DictController.java
  src/main/java/com/dogpamines/dogseek/main/controller/MainController.java
  src/main/java/com/dogpamines/dogseek/mypage/controller/MyPageController.java
  src/main/java/com/dogpamines/dogseek/products/controller/ProductsController.java
Labels: 🔨 Refactor
